// CPU

// fmt.Println("CPU:", infoStat.CPU)
// fmt.Println("VendorID:", infoStat.VendorID)
// fmt.Println("Family:", infoStat.Family)
// fmt.Println("Model:", infoStat.Model)
// fmt.Println("Stepping:", infoStat.Stepping)
// fmt.Println("PhysicalID:", infoStat.PhysicalID)
// fmt.Println("CoreID:", infoStat.CoreID)
// fmt.Println("Cores:", infoStat.Cores)
// fmt.Println("ModelName:", infoStat.ModelName)
// fmt.Println("Mhz:", infoStat.Mhz)
// fmt.Println("CacheSize:", infoStat.CacheSize)
// fmt.Println("Flags:", infoStat.Flags)
// fmt.Println("Microcode:", infoStat.Microcode)

// fmt.Println("CPU:", timesStat.CPU)
// fmt.Println("User:", timesStat.User)
// fmt.Println("System:", timesStat.System)
// fmt.Println("Idle:", timesStat.Idle)
// fmt.Println("Nice:", timesStat.Nice)
// fmt.Println("Iowait:", timesStat.Iowait)
// fmt.Println("Irq:", timesStat.Irq)
// fmt.Println("Softirq:", timesStat.Softirq)
// fmt.Println("Steal:", timesStat.Steal)
// fmt.Println("Guest:", timesStat.Guest)
// fmt.Println("GuestNice:", timesStat.GuestNice)

//

// Host

// fmt.Println("Hostname:", infoStat.Hostname)
// fmt.Println("Uptime:", infoStat.Uptime)
// fmt.Println("BootTime:", infoStat.BootTime)
// fmt.Println("Procs:", infoStat.Procs)
// fmt.Println("OS:", infoStat.OS)
// fmt.Println("Platform:", infoStat.Platform)
// fmt.Println("PlatformFamily:", infoStat.PlatformFamily)
// fmt.Println("PlatformVersion:", infoStat.PlatformVersion)
// fmt.Println("KernelVersion:", infoStat.KernelVersion)
// fmt.Println("KernelArch:", infoStat.KernelArch)
// fmt.Println("VirtualizationSystem:", infoStat.VirtualizationSystem)
// fmt.Println("VirtualizationRole:", infoStat.VirtualizationRole)
// fmt.Println("HostID:", infoStat.HostID)

// fmt.Println("SensorKey:", temperatureStat.SensorKey)
// fmt.Println("Temperature:", temperatureStat.Temperature)

// fmt.Println("User:", userStat.User)
// fmt.Println("Terminal:", userStat.Terminal)
// fmt.Println("Host:", userStat.Host)
// fmt.Println("Started:", userStat.Started)

// Load

// fmt.Println("Load1:", avgStat.Load1)
// fmt.Println("Load5:", avgStat.Load5)
// fmt.Println("Load15:", avgStat.Load15)

// fmt.Println("ProcsTotal:", miscStat.ProcsTotal)
// fmt.Println("ProcsCreated:", miscStat.ProcsCreated)
// fmt.Println("ProcsRunning:", miscStat.ProcsRunning)
// fmt.Println("ProcsBlocked:", miscStat.ProcsBlocked)
// fmt.Println("Ctxt:", miscStat.Ctxt)

// Mem

// fmt.Println("FreeBytes:", swapDevice.FreeBytes)
// fmt.Println("Name:", swapDevice.Name)
// fmt.Println("UsedBytes:", swapDevice.UsedBytes)

// fmt.Println("Free:", swapMemoryStat.Free)
// fmt.Println("PgFault:", swapMemoryStat.PgFault)
// fmt.Println("PgIn:", swapMemoryStat.PgIn)
// fmt.Println("PgMajFault:", swapMemoryStat.PgMajFault)
// fmt.Println("PgOut:", swapMemoryStat.PgOut)
// fmt.Println("Sin:", swapMemoryStat.Sin)
// fmt.Println("Sout:", swapMemoryStat.Sout)
// fmt.Println("Total:", swapMemoryStat.Total)
// fmt.Println("Used:", swapMemoryStat.Used)
// fmt.Println("UsedPercent:", swapMemoryStat.UsedPercent)

// fmt.Println("ActiveAnon:", virtualMemoryExStat.ActiveAnon)
// fmt.Println("ActiveFile:", virtualMemoryExStat.ActiveFile)
// fmt.Println("InactiveAnon:", virtualMemoryExStat.InactiveAnon)
// fmt.Println("InactiveFile:", virtualMemoryExStat.InactiveFile)
// fmt.Println("Unevictable:", virtualMemoryExStat.Unevictable)

// fmt.Println("Active:", virtualMemoryStat.Active)
// fmt.Println("Available:", virtualMemoryStat.Available)
// fmt.Println("Buffers:", virtualMemoryStat.Buffers)
// fmt.Println("Cached:", virtualMemoryStat.Cached)
// fmt.Println("CommitLimit:", virtualMemoryStat.CommitLimit)
// fmt.Println("CommittedAS:", virtualMemoryStat.CommittedAS)
// fmt.Println("Dirty:", virtualMemoryStat.Dirty)
// fmt.Println("Free:", virtualMemoryStat.Free)
// fmt.Println("HighFree:", virtualMemoryStat.HighFree)
// fmt.Println("HighTotal:", virtualMemoryStat.HighTotal)
// fmt.Println("HugePageSize:", virtualMemoryStat.HugePageSize)
// fmt.Println("HugePagesFree:", virtualMemoryStat.HugePagesFree)
// fmt.Println("HugePagesTotal:", virtualMemoryStat.HugePagesTotal)
// fmt.Println("Inactive:", virtualMemoryStat.Inactive)
// fmt.Println("Laundry:", virtualMemoryStat.Laundry)
// fmt.Println("LowFree:", virtualMemoryStat.LowFree)
// fmt.Println("LowTotal:", virtualMemoryStat.LowTotal)
// fmt.Println("Mapped:", virtualMemoryStat.Mapped)
// fmt.Println("PageTables:", virtualMemoryStat.PageTables)
// fmt.Println("Shared:", virtualMemoryStat.Shared)
// fmt.Println("SReclaimable:", virtualMemoryStat.SReclaimable)
// fmt.Println("Slab:", virtualMemoryStat.Slab)
// fmt.Println("SwapCached:", virtualMemoryStat.SwapCached)
// fmt.Println("SwapFree:", virtualMemoryStat.SwapFree)
// fmt.Println("SwapTotal:", virtualMemoryStat.SwapTotal)
// fmt.Println("Total:", virtualMemoryStat.Total)
// fmt.Println("Used:", virtualMemoryStat.Used)
// fmt.Println("UsedPercent:", virtualMemoryStat.UsedPercent)
// fmt.Println("VMallocChunk:", virtualMemoryStat.VMallocChunk)
// fmt.Println("VMallocTotal:", virtualMemoryStat.VMallocTotal)
// fmt.Println("VMallocUsed:", virtualMemoryStat.VMallocUsed)
// fmt.Println("Wired:", virtualMemoryStat.Wired)
// fmt.Println("Writeback:", virtualMemoryStat.Writeback)
// fmt.Println("WritebackTmp:", virtualMemoryStat.WritebackTmp)

// Net

// fmt.Println("Family:", connectionStat.Family)
// fmt.Println("Fd:", connectionStat.Fd)
// fmt.Println("Laddr:", connectionStat.Laddr)
// fmt.Println("Pid:", connectionStat.Pid)
// fmt.Println("Raddr:", connectionStat.Raddr)
// fmt.Println("Status:", connectionStat.Status)
// fmt.Println("Type:", connectionStat.Type)
// fmt.Println("Uids:", connectionStat.Uids)

// fmt.Println("Delete:", conntrackStat.Delete)
// fmt.Println("DeleteList:", conntrackStat.DeleteList)
// fmt.Println("Drop:", conntrackStat.Drop)
// fmt.Println("EarlyDrop:", conntrackStat.EarlyDrop)
// fmt.Println("Entries:", conntrackStat.Entries)
// fmt.Println("ExpectCreate:", conntrackStat.ExpectCreate)
// fmt.Println("ExpectDelete:", conntrackStat.ExpectDelete)
// fmt.Println("ExpectNew:", conntrackStat.ExpectNew)
// fmt.Println("Found:", conntrackStat.Found)
// fmt.Println("Ignore:", conntrackStat.Ignore)
// fmt.Println("IcmpError:", conntrackStat.IcmpError)
// fmt.Println("Insert:", conntrackStat.Insert)
// fmt.Println("InsertFailed:", conntrackStat.InsertFailed)
// fmt.Println("Invalid:", conntrackStat.Invalid)
// fmt.Println("New:", conntrackStat.New)
// fmt.Println("SearchRestart:", conntrackStat.SearchRestart)
// fmt.Println("Searched:", conntrackStat.Searched)

// fmt.Println("ConnTrackCount:", stat.ConnTrackCount)
// fmt.Println("ConnTrackMax:", stat.ConnTrackMax)

// fmt.Println("BytesRecv:", ioCountersStat.BytesRecv)
// fmt.Println("BytesSent:", ioCountersStat.BytesSent)
// fmt.Println("Dropin:", ioCountersStat.Dropin)
// fmt.Println("Dropout:", ioCountersStat.Dropout)
// fmt.Println("Errin:", ioCountersStat.Errin)
// fmt.Println("Errout:", ioCountersStat.Errout)
// fmt.Println("Fifoin:", ioCountersStat.Fifoin)
// fmt.Println("Fifoout:", ioCountersStat.Fifoout)
// fmt.Println("Name:", ioCountersStat.Name)
// fmt.Println("PacketsRecv:", ioCountersStat.PacketsRecv)
// fmt.Println("PacketsSent:", ioCountersStat.PacketsSent)

// fmt.Println("Addrs:", interfaceStat.Addrs)
// fmt.Println("Flags:", interfaceStat.Flags)
// fmt.Println("HardwareAddr:", interfaceStat.HardwareAddr)
// fmt.Println("Index:", interfaceStat.Index)
// fmt.Println("MTU:", interfaceStat.MTU)
// fmt.Println("Name:", interfaceStat.Name)

// fmt.Println("Protocol:", protoCountersStat.Protocol)
// fmt.Println("Stats:", protoCountersStat.Stats)
